
project_id = "iivoxaqqamovmagbwmeh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
port = 54323

[storage]
enabled = true

[auth]
enabled = true

[functions]
[functions.ai-chat]
verify_jwt = false

[functions.generate-report]
verify_jwt = true

[functions.send-report]
verify_jwt = true
