
project_id = "iivoxaqqamovmagbwmeh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[functions.ai-chat]
verify_jwt = true

[functions.generate-report]
verify_jwt = true

[functions.send-report]
verify_jwt = true

[functions.handle-appointment]
verify_jwt = true

[functions.create-trigger]
verify_jwt = true
